### ISSUE TITLE
callback passed to run() should be in node format (err, result)

### ISSUE THREAD

**Issue by bradvogel** [mixmaxhq/batchelor#12]
Currently run() throws exceptions when errors happen. See https://github.com/wapisasa/batchelor/blob/master/lib/batchelor.js#L167. It should call: `callback(new Error('..'))` instead. The result should be the second parameter of the callback.

**Comment by jamesmhaley** [comment]
:+1: Would you like to do the honours @bradvogel? Currently stuck on another project so might be a little while :)

**Comment by bradvogel** [comment]
Sure :)

**Comment by bradvogel** [comment]
See PR. Please push to npm :)
