### ISSUE TITLE
Getting response { parts: [], errors: 0 } regardless of what token we use for Bearer

### ISSUE THREAD

**Issue by brianjfernandes** [mixmaxhq/batchelor#2]
This may not be a bug on your part, just wondering if you've seen this? We've been using the access_token acquired by the usual oauth2 exchange auth code for tokens flow, server side. Is this even the correct token to use here? It seems no matter what we put in for Bearer we get this response. I would expect a 400 or 401 response, not { parts: [], errors: 0 } Thanks for any info you can provide!

**Comment by jamesmhaley** [comment]
What does your bearer token output as? What are you passing into Batchelor?

**Comment by brianjfernandes** [comment]
Hey James!

So we've been using the access_token server receives from the oauth2
process for email user we are sending batch requests on behalf of.  user
has authorized server for gmail
api. (gapi.oauth2Client.credentials.access_token).  I know token is valid
because I can access gmail api for other rest calls. Just having problems
with batch. Is this even the right token to use?

I put a debug console.log in batchelor.js at line 169 to dump responseObj.
There's a bunch of json, showing looks like metadata about the processed
request but in end, not the actual payloads for each request in the batch?
I've attached sample for your review. It also shows the bearer token
received. I looked a bit at the response - its interesting, looks like 5
segments each with associated post request - I think. my inbox has 7
messages and I know all 7 are being added to batch, so thats off.

Also, I seem to get same response regardless of what is set for bearer:
'123456' yields same result.

Thanks in advance for any help you can provide, really appreciate it.

-Brian

**Comment by jamesmhaley** [comment]
I didn't see anything attached to your message.

Please add https://www.npmjs.com/package/global-request-logger to the top of your script and paste the output into here, obviously removing any sensitive information, please leave the token structure as is, but change the contents (so that you are not giving away the keys to the kingdom).
