### ISSUE TITLE
Mocking batchelor requests with Nock

### ISSUE THREAD

**Issue by lewisblackwood** [mixmaxhq/batchelor#24]
Hey @jamesmhaley 👋 thanks for your great work on this library!

The official [Node JS Google client](https://github.com/google/google-api-nodejs-client) still doesn't support the batching endpoint 😞 so there's still a need for a lib such as this.

Currently, we use the Node JS Google client to interact with the the Google Calendar API. I've been using [Nock](https://github.com/node-nock/nock) to mock responses in our tests. Nock is also used for the tests in the official Google client too.

Unfortunately, Nock doesn't seem to pick up requests made by batchelor. I can see batchelor is using the request lib, which seems as though it should be compatible with nock.

Do you have any suggestions as to why Nock isn't picking up batchelor's requests?

I can provide an example to reproduce if that's helpful.

As an aside, how actively are you looking to maintain this lib? Would be keen to make some contributions if this is still being actively worked on! 👍

**Comment by lewisblackwood** [comment]
I've since looked into this a little further. The reason Nock doesn't work with Batchelor seems to be an issue with Nock handling `multipart` requests. It seems like there a [few workarounds](https://github.com/node-nock/nock/issues/887), so will try those out!

Would still be keen to help out on this project if it's actively maintained.

**Comment by jamesmhaley** [comment]
Hey @lewisblackwood, Thanks for that. Would love to have you onboard with the project! Been on other projects which means I no longer have the time to maintain as much as I would like. Looking to take this forward over the next few months. I'll add you to the repo.
