### ISSUE TITLE
default mimetype causes 400 errors with Google Calendar Batch API

### ISSUE THREAD

**Issue by hexsprite** [mixmaxhq/batchelor#25]
https://github.com/wapisasa/batchelor/blob/master/lib/batchelor.js#L49

the type is listed as `multipart/mixed;` -- NOTE: trailing semi-colon

I get 400 error from Google Calendar Batch API, but if I override the value without the semi-colon it works fine.

**Comment by jamesmhaley** [comment]
If you call other endpoints without the `;` does it fail??

Feel free to create a PR with a solution and myself or @bradvogel will merge it.
