### ISSUE TITLE
Google BATCH endpoints

### ISSUE THREAD

**Issue by jlippold** [mixmaxhq/batchelor#28]
Google is deprecating BATCH endpoints soon
https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html

Does this library use the `/batch/library/v1` suffix so it will continue to work after August 2020?

By looking at the source code, it seems like this is similiar to ![async](http://caolan.github.io/async/)

Does this library use /batch endpoints at all, or it is just special sauce to run multiple rest api calls in series or parallel and return the final output?

Thanks for the help!

**Comment by bradvogel** [comment]
Thanks for asking. Google is deprecating the global batch endpoint, so the example in the readme will no longer work:

```
var batch = new Batchelor({
	'uri':'https://www.googleapis.com/batch', // This URL won't work after August 2020
	'method':'POST',
	'auth': {
		'bearer': [... Google API Token ...]
	},
	'headers': {
		'Content-Type': 'multipart/mixed'
	}
});

```

Instead, you'll need to use a service-specific Batch URL in the format `https://www.googleapis.com/batch/<api>/<version>`, eg:

```
var batch = new Batchelor({
	'uri':'https://www.googleapis.com/batch/gmail/v1',
	'method':'POST',
	'auth': {
		'bearer': [... Google API Token ...]
	},
	'headers': {
		'Content-Type': 'multipart/mixed'
	}
});
```

I fixed the readme in https://github.com/wapisasa/batchelor/pull/29

**Comment by jlippold** [comment]
I can't get this to work. Im using the new batch format but it's failing, with an app crash. Pull request is here to fix the crash: https://github.com/wapisasa/batchelor/pull/30 and this is the code that causes the crash:

```
var batch = new Batchelor({
    'uri': 'https://www.googleapis.com/batch/classroom/v1/',
    'method': 'POST',
    'auth': {
        'bearer': results.client.credentials.access_token
    },
    'headers': {
        'Content-Type': 'multipart/mixed'
    }
});

results.courses.forEach(function (course, idx) {
    batch.add({
        'method': 'GET',
        'path': `courses/${course.extCourseId}/courseWork`
    })l
});

batch.run(function (err, response) {
    if (err) return next(err);
    next(err, response);
});
```

When I use the old style /batch endpoints it works as expected

```
var batch = new Batchelor({
    'uri': 'https://classroom.googleapis.com/batch/',
    'method': 'POST',
    'auth': {
        'bearer': results.client.credentials.access_token
    },
    'headers': {
        'Content-Type': 'multipart/mixed'
    }
});

results.courses.forEach(function (course, idx) {
    batch.add({
        'method': 'GET',
        'path': `/v1/courses/${course.extCourseId}/courseWork`
    })
});

batch.run(function (err, response) {
    if (err) return next(err);
    next(err, response);
});
```

Any idea what i'm doing wrong? I can't seem to craft the url in the proper form

**Comment by bradvogel** [comment]
answered in https://github.com/wapisasa/batchelor/pull/30#issuecomment-617476411
