### ISSUE TITLE
Will batchelor automatically split batches with more than 100 requests?

### ISSUE THREAD

**Issue by vladmiller** [mixmaxhq/batchelor#8]
Bathes are limited to 100 requests per batch, will bachelor automatically split requests?

If no, then it could be good feature,

**Comment by jamesmhaley** [comment]
Looking into this as and when we require it ourselves. It's a tough one as some Apis support 1000-per-request! 

Looking to add this over the next few months! Feel free to tackle it yourselves and pass on the love!
